tasks:
  - chat: -1001234567890     # 群组/频道 ID 或 @用户名
    time: "00:00"            # 每天的时间（24小时制）
    text: "赌狗签到"         # 发送的内容

  - chat: -1009876543210
    time: "09:00"
    text: "早安打卡"

  - chat: "@mytestgroup"     # 也可以直接用群/频道用户名
    time: "21:30"
    text: "晚安~"
